baseURL = '/'
languageCode = 'en-us'
title = 'Reddin.me'
theme = 'Mainroad-reddin'

[Author]
    name = "Will Reddin"
    bio = "Will has many interest."
    avatar = "img/jwt_1.png"

[Params]
    description = "A place on the internet for Will Reddin"
    authorbox = true
    twitter_cards = true
    googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts

[Params.logo]
    image = "img/jwt_1.png"

[Params.style.vars]
  highlightColor = "#666666" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.sidebar]
    home = "left"
    list = "left"
    single = "left"
    widgets = ["recent", "taglist", "social"]

[Params.widgets.social]
    linkedin = "williamreddin"
    github = "willreddin"
